/-
Copyright (c) 2026 Evan Chen, Kenny Lau, Ken Ono, Jujian Zhang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Evan Chen, Kenny Lau, Ken Ono, Jujian Zhang
-/

import LeanPool.FelConjecture.Solution

/-!
# Fel's Conjecture on Syzygies of Numerical Semigroups

A formal proof of Fel's conjecture relating gap power sums of a numerical
semigroup to invariants derived from its Hilbert series.

A numerical semigroup `S ⊆ ℕ` is an additive submonoid containing `0` with
finite complement (the *gaps* `Δ = ℕ \ S`). Given generators `{d₁,…,d_m}`
with `gcd = 1`, define
- gap power sums `G_r(S) = ∑_{g ∈ Δ} g^r`,
- the gap polynomial `Φ_S(z) = ∑_{g ∈ Δ} z^g`,
- the Hilbert series `H_S(z) = ∑_{s ∈ S} z^s`,
- the product polynomial `P_S(z) = ∏ᵢ (1 - z^{dᵢ})` and `π_m = ∏ᵢ dᵢ`,
- the Hilbert numerator `Q_S(z)` from `H_S(z) = Q_S(z) / P_S(z)`,
- alternating power sums `C_n(S) = ∑_{j ≥ 1} cⱼ · jⁿ` where
  `Q_S(z) = 1 - ∑_{j ≥ 1} cⱼ z^j`,
- invariants `K_p(S) = ((-1)^m · p!) / ((m+p)! · π_m) · C_{m+p}(S)`,
- and the symbols `T_n(σ)`, `T_n(δ)` from the generating series
  `A(t) = ∏ᵢ (e^{dᵢ t} - 1) / (dᵢ t)` and `B(t) = (t / (e^t - 1)) · A(t)`.

## Main result

- `fels_conjecture` — for every `p ≥ 0`,
  `K_p(S) = ∑_{r=0}^{p} (p choose r) · T_{p-r}(σ) · G_r(S)`
  `       + (2^{p+1} / (p+1)) · T_{p+1}(δ)`.

## Source

Imported from <https://github.com/AxiomMath/fel-polynomial> (paper:
[arXiv:2602.03716](https://arxiv.org/abs/2602.03716)). Initial code was
generated by [Axiom Math](https://axiommath.ai); see the upstream README
for full provenance.

## Authors

Evan Chen, Kenny Lau, Ken Ono, Jujian Zhang.

## Status

Imported from upstream `AxiomMath/fel-polynomial` at Lean v4.26.0 / Mathlib
v4.26.0. Lean Pool pins v4.30.0-rc2; the source is being ported to the
newer Mathlib API in this PR. Upstream contains no `sorry`s in the
solution file.
-/
